version: "3.8"

services:
  api:
    container_name: arom-web-services
    ports:
      - "8000:8000"
    build:
      context: ./
      dockerfile: ./docker/dev.Dockerfile
    environment:
      SERVER_PORT: 8000
    volumes:
      - ./:/app
#   postgres:
#     image: postgres:latest
#     container_name: postgres
#     environment:
#       POSTGRES_DB: ${DB_NAME}
#       POSTGRES_USER: ${DB_USER}
#       POSTGRES_PASSWORD: ${DB_PASSWORD}
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     ports:
#       - "${DB_PORT}:5432"
#     restart: unless-stopped

#   pgadmin:
#     image: dpage/pgadmin4:latest
#     container_name: pgadmin
#     environment:
#       PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
#       PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}
#     ports:
#       - "5050:80"
#     depends_on:
#       - postgres
#     restart: unless-stopped

# volumes:
#   postgres_data:
